"""Add camera in-out config table

Revision ID: da251bb062c7
Revises: fd7724d10aab
Create Date: 2026-04-22 20:33:09.399152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da251bb062c7'
down_revision: Union[str, None] = 'fd7724d10aab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera_in_out_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('camera_id', sa.String(), nullable=False),
    sa.Column('p1_x', sa.Integer(), nullable=False),
    sa.Column('p1_y', sa.Integer(), nullable=False),
    sa.Column('p2_x', sa.Integer(), nullable=False),
    sa.Column('p2_y', sa.Integer(), nullable=False),
    sa.Column('in_side', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.camera_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('camera_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('camera_in_out_config')
    # ### end Alembic commands ###
