"""Add camera extra tables

Revision ID: fd7724d10aab
Revises: d3e492f10d22
Create Date: 2026-04-22 18:08:02.752674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd7724d10aab'
down_revision: Union[str, None] = 'd3e492f10d22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera_features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('camera_id', sa.String(), nullable=False),
    sa.Column('feature_name', sa.String(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.camera_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('camera_metadata',
    sa.Column('camera_id', sa.String(), nullable=False),
    sa.Column('floor', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.camera_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('camera_id')
    )
    op.create_table('camera_modules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('camera_id', sa.String(), nullable=False),
    sa.Column('module_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.camera_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('camera_modules')
    op.drop_table('camera_metadata')
    op.drop_table('camera_features')
    # ### end Alembic commands ###
